### ISSUE TITLE
Hvilke filtreringsmuligheder skal fire-gama have?

### ISSUE THREAD

**Issue by AsgerPetersen** [Septima/fire-gama#1]
Man må formode, at der vil være behov for at filtrere i hvilke  `Observation`er, programmet skal eksportere.

Kan @kbevers eller @busstoptaktik måske komme med nogle bud?

**Comment by busstoptaktik** [comment]
Først og fremmest skal man kunne søge efter observationer defineret ved afstand fra et centerpunkt og indenfor en tidsramme.

I første omgang er det, hvad observationer angår, kun højdeforskelle der er  interessante (afsnit 2.15 i GAMAmanualen). Parametren stdev="..." beregnes som kvadratroden af totalvariansen fra databasen.

For koordinater er det DVR90-koter der er interessante. 

Derudover skal vi bruge placeringskoordinater - ved udvælgelse bruges placeringskoordinaten som søgekriterium. Derudover bruges den til plot af oversigtsplot.

Demofilen mikhail-7.4.gkf fra GAMA-eksempelsamlingen er et godt første bud på outputformat (dog skal stdev="..." tilføjes for hver observation og plankoordinater for hver punktdefinition).

**Comment by AsgerPetersen** [comment]
@busstoptaktik 

Skal det forstås som at vi kun skal koncentrere os om observationstypen `geometrisk_koteforskel` indtil videre? Og at stddev skal sættes til `sqrt(VALUE7)` fra den pågældende observation (idet `VALUE7` er beskrevet som `Total varians koteforskel [m^2]` for denne observationstype)?

**Comment by busstoptaktik** [comment]
@kbevers - kan du gennemskue hvordan dette passer sammen med at vi i går snakkede om at eliminere totalvarians i alle observationstyper?

Skal stdev beregnes som n*c + sqrt(l)*d hvor l er sigtelængde (i km), n er antal opstillinger (dimensionsløst), c er centreringsfejlen (mm) og d er den afstandsafhængige fejl (mm/sqrt(km), alias "nivellementsenheder", ne) - eller er c og d givet i "varianslignende" enheder (mm^2, hhv. mm^2/km), så udtrykket bliver stdev = sqrt(n*c + l*d)?

**Comment by kbevers** [comment]
Ja, det kan jeg godt. Den totale varians, som lige nu gemmes i `VALUE7` kan også udtrykkes ved: `(VALUE5+VALUE6)/ANTAL` eller med rigtige ord "Afstandsuafhængig fejl plus afstandsafhængig fejl divideret med antallet af satser". Standardafvigelsen der skal bruges i Gnu Gama bliver så `sqrt((VALUE5+VALUE6)/ANTAL)`.

Trigonometriske koteforskelle bør også tages med. Her bliver udtrykket for standardafvigelsen `sqrt((VALUE4+VALUE5)/ANTAL)`. Igen er det afstandsuafhængig plus afstandsafhængig fejl divideret med antallet af satser.
