### ISSUE TITLE
Udvægelse af observationer

### ISSUE THREAD

**Issue by klavspc** [Septima/fire-gama#2]
Fra https://github.com/Septima/fire-gama/issues/1#issuecomment-443729720:

> Først og fremmest skal man kunne søge efter observationer defineret ved afstand fra et centerpunkt og indenfor en tidsramme.

Centerpunkt: Er det en koordinat eller id på et punkt i fire?
Hvis begge dele skal være muligt: Hvilken har første-prioritet i første version?

**Comment by busstoptaktik** [comment]
Første prioritet er givetvis koordinat - sådan en kan man altid finde ud fra "klik på et kort"
