### ISSUE TITLE
Udvælgelse af fix-punkter

### ISSUE THREAD

**Issue by klavspc** [Septima/fire-gama#3]
`<point id="7CA9F53D-DBEE-59C0-E053-1A041EAC5678" ... .... .. ... fix="z" />`

Er der noget der karakteriserer de punkter, der skal bruges som fixpunkter eller skal disse angives som parameter til fire-gama?

**Comment by busstoptaktik** [comment]
Nej - det er operatøren der ud fra sin enorme erfaring udvælger de rette punkter.

Den fil der udtrækkes vil i praksis blive efterredigeret af en fagperson, som vælger hvad der skal fastholdes og hvad der skal - som det i en ret morsom fagjargon kaldes - "friholdes". ... jamen noget skal det jo hedde når man har brug for at tale om det

**Comment by klavspc** [comment]
@busstoptaktik 

> Den fil der udtrækkes vil i praksis blive efterredigeret af en fagperson, som vælger hvad der skal fastholdes 

Betyder det, at fire-gama blot skal outputte alle punkter og så bliver der efter redigeret? Det kan jo potentielt blive en stor fil.

Det vil være muligt, og måske bedre for operatøren, at de punkter, der skal fastholdes står i en separat opsætningsfil. Det vil bestemt være en mulig udvidelse af fire-gama
