### ISSUE TITLE
fire-gama, output

### ISSUE THREAD

**Issue by klavspc** [Septima/fire-gama#4]
Fra https://github.com/Septima/fire-gama/issues/1#issuecomment-443729720

> Demofilen mikhail-7.4.gkf fra GAMA-eksempelsamlingen er et godt første bud på outputformat (dog skal stdev="..." tilføjes for hver observation og plankoordinater for hver punktdefinition).

Fra mikhail-7.4.gkf;
`<dh from="D" to="E" val=" 21.32" dist="13.5" />`
* Hvordan beregnes/findes _dist_?

Fra mikhail-7.4.gkf;
`<point id="B"             adj="z" />`

- Det er i ovenstående, at koordinater ønskes indsat?
- Hvad skal de bruges til?
- Hvad, hvis der for visse punkter ikke er koordinater; gør det noget?

**Comment by busstoptaktik** [comment]
@klavspc, @kbevers:  Hov - ser nu lige i morgenens klarsyn oven på en nats søvn at jeg, i min iver for at mødes så hurtigt som muligt, har fået plantet mødeforslagstidspunktet direkte oven i alt hvad der med rimelighed ligner en frokostpause. Måske 13:30 er et bedre tidspunkt?

mvh Thomas

**Comment by kbevers** [comment]
> Hvordan beregnes/findes dist?

Den gemt som observation.value2, bemærk dog at den er gemt i meter og gama skal bruge værdien i kilometer. Så observation.value2/1000.

> Det er i ovenstående, at koordinater ønskes indsat?
> Hvad skal de bruges til?
> Hvad, hvis der for visse punkter ikke er koordinater; gør det noget?

Ja, forudsat der findes en koordinat til punktet. Det vil der ofte gøre, men ikke nødvendigvis (fx hvis man bruger gama til at bestemme et punkts koordinat).
