### ISSUE TITLE
Validering af stddev i output

### ISSUE THREAD

**Issue by klavspc** [Septima/fire-gama#5]
Allerførste hul igennem fra fire til output.xml har givet et output
`<dh from="7CA9F53D-DF5B-59C0-E053-1A041EAC5678" to="7CA9F53D-DF5A-59C0-E053-1A041EAC5678" val="-4.99261" dist="?" stdev="0.0010074244388538526" />`

Ser værdien for stddev fornuftig ud?
Python:
`dev=math.sqrt((observation.value5 + observation.value6)/observation.antal)`

**Comment by busstoptaktik** [comment]
Det lyder ikke usandsynligt at spredningen på en observation (som jo er akkumuleret over flere opstillinger) når millimeterniveau - men jeg har ikke SQLderbredden til at checke op mod de faktiske tal. Måske @kbevers kan?

Det bekymrer mig lidt at `dist=?` da afstanden indgår i beregningen af den afstandsafhængige spredning, men jeg må tilstå at jeg ikke kan huske hvordan vi valgte at repræsentere det, så det kan være det er OK. Ellers skal dist beregnes ud fra geometritabellen

**Comment by klavspc** [comment]
@busstoptaktik 
> Det bekymrer mig lidt at dist=?

Det er mig, der har sat dist til "?" indtil jeg ved, hvordan den skal beregnes/findes

**Comment by kbevers** [comment]
> dev=math.sqrt((observation.value5 + observation.value6)/observation.antal)

Ovenstående udtryk er korrekt.

Hvad angår `dist` så er den gemt som `observation.value2`, bemærk dog at den er gemt i meter og gama skal bruge værdien i kilometer. Så `observation.value2/1000`.
