### ISSUE TITLE
Pythonpakke

### ISSUE THREAD

**Issue by kbevers** [Septima/fire-gama#7]
Det er på nuværende tidspunkt ikke muligt at installere fire-gama, fx med `pip` eller `python setup.py install`. Det forudsætter flere ting, blandt andet at fireapi er installeret (muligt ved brug af https://github.com/Septima/fikspunktsregister/pull/78) og med stor sandsynlighed lidt omstrukturering i repositoriet (der bør være en `fire-gama` mappe i roden hvor bibliotekskode og cli bor). En væsentligt del af installationen er at `fire-gama` CLI'en bliver installeret sådan at man kan kalde (fx) `firegama` i en terminal uden at skulle være i en bestemt mappe.

**Comment by AsgerPetersen** [comment]
@klavspc er denne ikke fikset?

**Comment by AsgerPetersen** [comment]
Burde være fikset med b3f94b040e49d253ebe2f392fa508d1a8e4533c8
